openapi: 3.0.0
info:
  title: Data Reading API
  description: API module for reading patient health data
  version: "1.0"
servers:
  - url: https://health-monitoring-system.com/api

paths:
  /patients/{patientId}/measurements:
    get:
      summary: Get measurements for a specific patient
      operationId: getPatientMeasurements
      parameters:
        - name: patientId
          in: path
          required: true
          description: Unique identifier of the patient
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          description: Start date for filtering measurements
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: false
          description: End date for filtering measurements
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of patient measurements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
        '404':
          description: Patient not found

components:
  schemas:
    Measurement:
      type: object
      properties:
        type:
          type: string
          description: Type of measurement (e.g., blood pressure, temperature)
        value:
          type: number
          description: The value of the measurement
        unit:
          type: string
          description: Unit of the measurement value (e.g., mmHg, °C)
        timestamp:
          type: string
          format: date-time
          description: When the measurement was taken
